name: Good Karma Coffee
favicon: null
layout_spectrum: 0.87757
typography_spectrum: 0.59107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0d2b5'
    - '#453b2f'
    - '#8d933b'
    - '#c8ca4f'
    - '#8a95b1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
