name: Good Karma Coffee
favicon: null
layout_spectrum: 0.74828
typography_spectrum: 0.62095
title: Good Karma Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#221318'
    - '#54433a'
    - '#96a061'
    - '#7d7560'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
