name: Good Karma Coffee
favicon: null
layout_spectrum: 0.97356
typography_spectrum: 0.09794
title: Good Karma Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12110d'
    - '#53502d'
    - '#817485'
    - '#ad9b8d'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
