analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#abc15c'
    - '#0b0f0e'
    - '#7a5a5b'
    - '#929a68'
  brandStrength: 1
  lightness: 0.659628
  rhythmicContrast: 0.683277
  saturation: 0.180743
cta: {}
layout_spectrum: 0.103041
name: Good Karma Coffee
opengraph: {}
purpose: []
typography_spectrum: 0.62095
