name: Good Karma Coffee
favicon: null
layout_spectrum: 0.50344
typography_spectrum: 0.58961
title: Good Karma Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12110d'
    - '#53502d'
    - '#817485'
    - '#ad9b8d'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
