name: Good Karma Coffee
favicon: null
layout_spectrum: 0.22526
typography_spectrum: 0.09989
title: Good Karma Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#3a3532'
    - '#b5613f'
    - '#999a8b'
    - '#feb4a0'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
