name: Good Karma Coffee
favicon: null
layout_spectrum: 0.5517
typography_spectrum: 0.59107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c3c1a8'
    - '#cee2fa'
    - '#ab9e7e'
    - '#688ebb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
