analytics: {}
color:
  brandColors:
    - '#B9BABC'
    - '#989E84'
    - '#515321'
    - '#093C57'
    - '#955555'
  brandStrength: 0.505912
  lightness: 0.706926
  rhythmicContrast: 0.498311
  saturation: 0.345439
cta: {}
layout_spectrum: 0.496622
name: Good Karma Coffee
opengraph: {}
purpose: []
typography_spectrum: 0.62095
