analytics: {}
color:
  brandColors:
    - '#C8C0A8'
    - '#280810'
    - '#705858'
    - '#988040'
    - '#000000'
  brandStrength: 1
  lightness: 0.659628
  rhythmicContrast: 0.683277
  saturation: 0.180743
cta: {}
layout_spectrum: 0.782939
name: Good Karma Coffee
opengraph: {}
purpose: []
typography_spectrum: 0.62095
