name: Good Karma Coffee
favicon: null
layout_spectrum: 0.89519
typography_spectrum: 0.62095
title: Good Karma Coffee Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#abc15c'
    - '#0b0f0e'
    - '#7a5a5b'
    - '#929a68'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
