analytics: {}
color:
  brandColors:
    - '#C8C0A8'
    - '#280810'
    - '#705858'
    - '#988040'
    - '#000000'
  brandStrength: 0.505912
  lightness: 0.923986
  rhythmicContrast: 0.324324
  saturation: 0.185811
cta: {}
layout_spectrum: 0.439189
name: Good Karma Coffee
opengraph: {}
purpose: []
typography_spectrum: 0.62095
